### PR TITLE
PR for #26: Discuss creation of setup.sh

### PR DESCRIPTION
**Pull request by lucamlouzada**
**Closes** #26

**Changes and deliverables:**
In issue #26, we created `setup.sh`. The idea is that this script should be run after a user first clones a repository. See https://github.com/gentzkow/GentzkowLabTemplate/issues/26#issuecomment-2453177315 and https://github.com/gentzkow/GentzkowLabTemplate/issues/26#issuecomment-2458354773 for the discussion of what we were aiming to achieve with this script. We also made minor fixes to `get_inputs.sh` and `.gitignore`, and larger fixes to `make_externals.sh` to ensure zsh and bash consistency.

**Review**
Other than reviewing the changes and testing the overall logic of the new script, it'd be great to test the robustness for errors in the spirit of #19. In particular, we have been noticing some inconsistencies for users that run the template scripts on bash vs zsh (see e.g https://github.com/gentzkow/GentzkowLabTemplate/issues/26#issuecomment-2460592304), and so it would be great for the review to include testing those two shells.

I am requesting a review from @ShiqiYang2022. Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by ShiqiYang2022** [comment]
We are getting close ... 😄 I will review it tomorrow!

**Review by ShiqiYang2022 — CHANGES_REQUESTED** [review]
Thanks @lucamlouzada! 

These changes all looks good from my side, except that when I run `setup.sh` from the root of repo, it will create the `/input/` under the root instead of the related module (and the `/input/` folder contains nothing). 

Per offline conversation, this seems to be the only hurdle. After we resolve this, I am willing to approve.

**Comment by lucamlouzada** [comment]
Thanks @ShiqiYang2022 ! I pushed a change to `setup.sh` that should fix this issue; we now cd into each module before running `get_inputs.sh` so it should be consistent regardless from where you call `setup.sh` from. The paths in `get_inputs.sh` should always be relative to the current module so I pushed a change to the instructions to reflect that.

**Review by ShiqiYang2022 — APPROVED** [review]
All looks good, thanks @lucamlouzada very much!

**Pull request merged**
